---
- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
      gcp_project: basecamp-homework
      gcp_cred_kind: serviceaccount
      gcp_cred_file: /home/user/creds.json
      zone: "europe-central2-b"
      region: "europe-central2"

      disks: 
        - disk-host-1
        - disk-host-2
        - disk-host-3
        - disk-host-4
      addresses:
        - address-1
        - address-2
        - address-3
        - address-4
  tasks:
   - name: create a disk
     gcp_compute_disk:
        name: "{{ item }}"
        size_gb: 10
        source_image: 'projects/debian-cloud/global/images/debian-10-buster-v20210512'
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
           - https://www.googleapis.com/auth/compute
        state: present  
     loop: "{{ disks }}"
     register: disk

   - name: create a network
     gcp_compute_network:
        name: 'network-instance'
        auto_create_subnetworks: 'true'
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
         - https://www.googleapis.com/auth/compute
        state: present
     register: network
#   - name: create a subnetwork
#     gcp_compute_subnetwork:
#       name: ansiblenet
#       region: "{{ region }}"
    #   network: "{{ network }}"
#       ip_cidr_range: 192.168.1.0/29
#       project: "{{gcp_project}}"
#       auth_kind: serviceaccount
#       service_account_file: "/home/user/creds.json"
#       state: present

   - name: create a address
     gcp_compute_address:
        name: "{{ item }}"
        region: "{{ region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
     loop: "{{ addresses }}"
     register: address
   - name: create a instance
     gcp_compute_instance:
         state: present
         name:  "{{ item.name }}"
         machine_type: n1-standard-1
         disks:
           - auto_delete: true
             boot: true
             source: "{{ item.disk }}"
         network_interfaces:
             - network: "{{ network }}"
               access_configs:
                 - name: 'External NAT'
                   #nat_ip: "{{ item.address }}"
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
     loop: 
       - { name: 'host-1', address: "{{ address.results[0] }}", disk: "{{ disk.results[0] }}" }
       - { name: 'host-2', address: "{{ address.results[1] }}", disk: "{{ disk.results[1] }}" }
       - { name: 'host-3', address: "{{ address.results[2] }}", disk: "{{ disk.results[2] }}" }
       - { name: 'host-4', address: "{{ address.results[3] }}", disk: "{{ disk.results[3] }}" }
      
